Repository sonata-project/SonataNewsBundle, pull requests merged in 2018-06, with the labels that each got.

#456 #454 pagination swap prev-next link destination (fix)
  src/Resources/views/Post/archive.html.twig
Labels: patch

#457 Use ADR pattern
  src/Action/AbstractPostArchiveAction.php
  src/Action/CollectionPostArchiveAction.php
  src/Action/CommentListAction.php
  src/Action/CreateCommentAction.php
  src/Action/CreateCommentFormAction.php
  src/Action/ModerateCommentAction.php
  src/Action/MonthlyPostArchiveAction.php
  src/Action/PostArchiveAction.php
  src/Action/TagPostArchiveAction.php
  src/Action/ViewPostAction.php
  src/Action/YearlyPostArchiveAction.php
  src/Controller/PostController.php
  src/DependencyInjection/SonataNewsExtension.php
  src/Resources/config/actions.xml
  src/Resources/config/routing/news.xml
  src/Resources/views/Post/view.html.twig
Labels: minor

#462 Fixed wrong route parameter
  src/Action/CollectionPostArchiveAction.php
Labels: patch

#463 Fixed PHPDoc
  src/Model/CommentInterface.php
  src/Model/PostInterface.php
Labels: pedantic

#459 Make posts visible to admins with status message
  src/Action/ViewPostAction.php
  src/Resources/config/actions.xml
  src/Resources/translations/SonataNewsBundle.de.xliff
  src/Resources/translations/SonataNewsBundle.en.xliff
  src/Resources/views/Post/view.html.twig
Labels: minor
