Repository sonata-project/SonataNewsBundle, pull requests merged in 2019-05, with the labels that each got.

#520 Added events to comment action
  composer.json
  src/Action/CreateCommentAction.php
  src/Event/CommentEvent.php
  src/Event/FilterCommentResponseEvent.php
  src/Event/FormEvent.php
  src/Event/GetResponseCommentEvent.php
  src/Resources/config/actions.xml
  src/SonataNewsEvents.php
Labels: minor

#528 Applied fixes from FlintCI
  tests/Controller/Api/CommentControllerTest.php
  tests/Controller/Api/PostControllerTest.php
  tests/Entity/CommentManagerTest.php
  tests/Entity/PostManagerTest.php
  tests/Permalink/CollectionPermalinkTest.php
  tests/Permalink/DatePermalinkTest.php
Labels: pedantic

#529 Twig deprecation notice
  composer.json
  src/Twig/Extension/NewsExtension.php
Labels: patch
